version: "3"
services:
  hub:
    image: selenium/hub:3.14   
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: manikannanmarimuthu/sel-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=testng_search.xml
    volumes:
      - D:/Docker/Workspace/TestRunner/Output/test-duck:/usr/share/dockertest/test-output
  book-ticket-module:
    image: manikannanmarimuthu/sel-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=testng_mercury.xml
    volumes:
      - D:/Docker/Workspace/TestRunner/Output/test-mercury:/usr/share/dockertest/test-output